name: Release
on:
    release:
        types: [created]
jobs:
    ci:
        name: CI Checks
        uses: ./.github/workflows/ci.yaml
    docs:
        name: Docs
        uses: ./.github/workflows/deploy-docs.yaml
    release:
        name: Release
        uses: ./github/workflows/release-common.yaml
        needs: ci
        secrets: inherit
